if [ -f /usr/local/lib/standard/bashrc ]; then
    . /usr/local/lib/standard/bashrc
fi

[[ $- != *i* ]] && return

export LANG='en_US.UTF-8'
export EDITOR='vim'

alias rm='rm -i'
alias l='ls'
alias la='ls -a'
alias ll='ls -la'
alias ls='ls -G'

alias v='vi'
alias vi='vim'

export PS1='\h:\[$(tput bold)\]\W\$\[$(tput sgr0)\] '

date

