if [ -f /usr/local/lib/standard/bashrc ]; then
    . /usr/local/lib/standard/bashrc
fi

[[ $- != *i* ]] && return

export LANG='en_US.UTF-8'
export EDITOR='vim'
unset HISTFILE
unset HISTSIZE
unset HISTFILESIZE

alias rm='rm -i'
alias ls='ls -G'
alias x='exit'
alias q='exit'
alias ':q'='exit'

alias vi='vim'

export PS1='\h:\[$(tput bold)\]\W\$\[$(tput sgr0)\] '

echo `LANG=C date`
