if !1 | finish | endif

scriptencoding utf-8

" mask unused plugins
let g:loaded_getscriptPlugin = 1
let g:loaded_logiPat = 1
let g:loaded_spellfile_plugin = 1
let g:loaded_2html_plugin = 1
let g:loaded_vimballPlugin = 1

" basic options
set autoindent
set autoread
set autowriteall
set backspace=indent
set completeopt& completeopt-=preview
set expandtab
set fileencodings=utf-8,ucs-bom,iso-2022-jp,euc-jp,cp932,default,latin
set foldmethod=manual
set laststatus=2
set list
set listchars=tab:>.,trail:~,nbsp:%
set magic
set modeline
set mouse-=a
set nocursorline
set nocursorcolumn
set nofoldenable
set number
set numberwidth=5
set showmatch
set smartindent
set splitbelow
set updatetime=1000
set wrap
set statusline=%f%(\ %M%R%)
set statusline+=%=\ \ 
set statusline+=%{(&ft!=''?&ft:'plain').':'.(&fenc!=''?&fenc:&enc).':'.&ff}\ [%2B]\ %v:%l/%L

if (v:version >= 704) && has('patch338')
    set breakindent
endif

" color scheme
colorscheme desert
highlight CursorLineNR cterm=bold

" rubyなファイルがストレスレスに開くようになる魔法の呪文
" 代償として、補完が少し弱くなる
let g:ruby_path = ""

" keymaps
nnoremap <silent> <C-n> gt
nnoremap <silent> <C-p> gT
nnoremap <silent> <C-w>t :tabnew<CR>
nnoremap <silent> <C-w>" :split<CR>
nnoremap <silent> <C-w>% :vsplit<CR>

nnoremap <silent> <C-k><C-n> :setlocal number!<CR>
nnoremap <silent> <C-k><C-r> :setlocal readonly!<CR>
nnoremap <silent> <C-k><C-p> :setlocal paste!<CR>:echo 'paste='.&paste<CR>
nnoremap <silent> <C-k><C-e> :setlocal expandtab!<CR>:echo 'expandtab='.&expandtab<CR>

inoremap <silent> <C-w><C-w> <Esc>

nnoremap <silent> <C-k><C-l> :Explore<CR>

" tabs
set shiftwidth=4
set softtabstop=4
set tabstop=4
syntax on
set nobackup
set noswapfile
"set noundofile

