if !1 | finish | endif

scriptencoding utf-8

" !!! taken from 01-options.vim !!!
set autoindent
set autoread
set autowriteall
set completeopt& completeopt-=preview
set expandtab
set fileencodings=utf-8,ucs-bom,iso-2022-jp,euc-jp,cp932,default,latin
set foldmethod=manual
set laststatus=2
set list
set listchars=tab:>.,trail:~,nbsp:%
set magic
set modeline
set mouse-=a
set nocursorline
set nocursorcolumn
set nofoldenable
set number
set numberwidth=5
set showmatch
set smartindent
set splitbelow
set updatetime=1000
set wrap
set statusline=%f%(\ %M%R%)
set statusline+=%=\ \ 
set statusline+=%{(&ft!=''?&ft:'plain').':'.(&fenc!=''?&fenc:&enc).':'.&ff}\ [%2B]\ %v:%l/%L

if (v:version >= 704) && has('patch338')
    set breakindent
endif

" color scheme
colorscheme desert
highlight CursorLineNR cterm=bold

" rubyなファイルがストレスレスに開くようになる魔法の呪文
" 代償として、補完が少し弱くなる
let g:ruby_path = ""


" !!! taken from 02-keybinds.vim !!!
nnoremap <silent> <F5> :tabedit $MYVIMRC<CR>
nnoremap <silent> <F6> :source $MYVIMRC<CR>
nnoremap x "_x
nnoremap X "_X
nnoremap Y "+y
nnoremap YY "+yy
nnoremap - "+p
nnoremap _ "+P
nnoremap t ge
nnoremap T gE
nnoremap <silent> <C-n> gt
nnoremap <silent> <C-p> gT
nnoremap <silent> [ %
nnoremap <expr> <C-w>T ":vsplit " . tempname() . "\<CR>"
nnoremap <silent> <C-w>x <C-w>q
nnoremap <silent> <C-w><C-n> gt
nnoremap <silent> <C-w><C-p> gT
nnoremap <silent> <C-k><C-n> :setlocal number!<CR>
nnoremap <silent> <C-k><C-r> :setlocal readonly!<CR>
nnoremap <silent> <C-k><C-p> :setlocal paste!<CR>:echo 'paste='.&paste<CR>
nnoremap <silent> <C-k><C-e> :setlocal expandtab!<CR>:echo 'expandtab='.&expandtab<CR>
inoremap <silent> <C-w><C-n> <Esc>gt
inoremap <silent> <C-w><C-p> <Esc>gT
inoremap <silent> <C-w><C-w> <Esc>
vnoremap Y "+y


" !!! univ vimrc specific !!!
syntax on
set nobackup
set noswapfile
"set noundofile
imap <expr> <C-n> pumvisible() ? "\<C-n>" : "\<C-x>\<C-u>\<C-p>"

