# ~/.profile

if test -z "${DISPLAY}"
then
  echo -n "startx? [Y/n] > "
  entry=""
  read entry
  if test "${entry}" \!= "n" && test "${entry}" \!= "N"
  then
    exec startx
  fi
fi

source ${HOME}/.bashrc
