#!/bin/sh

export LANG="en_US.UTF-8"
export PATH="${HOME}/.local/bin:${PATH}"

# automatically startx
[ -z "${DISPLAY}" ] && exec startx

# source init.sh if startx not execed
. "${HOME}/.config/ash/init.sh"
