#!/bin/sh

if test -d /etc/X11/xinit/xinitrc.d
then
   for file in /etc/X11/xinit/xinitrc.d/*
   do
      test -x "${file}" && source "${file}"
   done
   unset file
fi

/usr/bin/amixer set Master off &
/usr/bin/amixer set Master 0 &
/usr/bin/xbacklight =5% &
export LANG='ja_JP.UTF-8'
export XMODIFIERS='@im=fcitx'
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
/usr/bin/fcitx
/usr/bin/xmodmap ${HOME}/.Xmodmap
exec /usr/bin/ratpoison
