#!/bin/sh

if test -d /etc/X11/xinit/xinitrc.d
then
   for file in /etc/X11/xinit/xinitrc.d/*
   do
      test -x "${file}" && . "${file}"
   done
   unset file
fi

export LANG='ja_JP.UTF-8'
export XMODIFIERS='@im=uim'
export GTK_IM_MODULE='uim'
export QT_IM_MODULE='uim'

# hack for various Java AWT bugs
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

uim-xim &
${HOME}/.local/bin/dwm-updateinfo &
/usr/bin/xmodmap ${HOME}/.config/Xmodmap
xbacklight -set 20 &
autocutsel -selection PRIMARY -fork &
autocutsel -selection SECONDARY -fork &
autocutsel -selection CLIPBOARD -fork &
feh --bg-center --no-fehbg ${HOME}/.local/wallpaper.png
exec ${HOME}/.local/bin/dwm
