#!/bin/sh
export LANG='ja_JP.UTF-8'

case "$PATH" in
	*$HOME/.local/bin*) ;;
	*) export PATH="${HOME}/.local/bin:${PATH}";;
esac

# keyboard settings
xset r rate 200 45 &
setxkbmap -option ctrl:nocaps -option altwin:prtsc_rwin &

# ime
command -v fcitx-autostart >/dev/null && {
	export XMODIFIERS=@im=fcitx
	export QT_IM_MODULE=fcitx
	export GTK_IM_MODULE=fcitx
	fcitx-autostart &
}

# touchpad
command -v xinput >/dev/null && (
	DEVID=$(xinput list --id-only 'SynPS/2 Synaptics TouchPad')
	xinput set-prop $DEVID 'libinput Tapping Enabled' 1
	xinput set-prop $DEVID 'libinput Tapping Drag Enabled' 1
	xinput set-prop $DEVID 'libinput Middle Emulation Enabled' 1
	xinput set-prop $DEVID 'libinput Natural Scrolling Enabled' 1
	xinput set-prop $DEVID 'libinput Click Method Enabled' 0 1
	xinput set-prop $DEVID 'libinput Accel Speed' 0.5
) &

autostart () {
	(command -v $1 >/dev/null || return
	app=$1
	shift 1
	pkill $app
	$app "$@" &
	)
}

# hack for beautiful looking in Java, avoid Java AWT bugs
export _JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=gasp'
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
autostart wmname LG3D

# misc autostart
autostart redshift
autostart dwm-statusline forever
autostart xss-lock -- slock
[ -x "${HOME}/.local/wallpaper.sh" ] \
	&& autostart "${HOME}/.local/wallpaper.sh"

# compositor
[ "$(command -v compton)" -a -f "${HOME}/.config/compton.conf" ] \
	&& compton --config "${HOME}/.config/compton.conf" --daemon

## mi notebook air 13, sharp; https://github.com/tlvince/xiaomi-mi-notebook-air-13
[ -f "${HOME}/.config/6500k.icm" ] \
	&& autostart dispwin -d1 "${HOME}/.config/6500k.icm"

# workaround for lock file
[ -f "${HOME}/Drive/.Passwords.kdbx.lock" ] \
	&& rm -f "${HOME}/Drive/.Passwords.kdbx.lock"
autostart keepassxc ${HOME}/Drive/Passwords.kdbx

unset -f autostart

