#!/bin/sh
if test -d /etc/X11/xinit/xinitrc.d
then
   for file in /etc/X11/xinit/xinitrc.d/*
   do
      test -x "${file}" && . "${file}"
   done
   unset file
fi

[ -f /etc/xprofile ] && . /etc/xprofile

. "$HOME/.xprofile"

command -v ssh-agent >/dev/null \
	&& exec ssh-agent dwm

exec dwm

